source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "iOSApp" do
  pod 'Alamofire', '~> 3.1.4'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
  pod 'HanekeSwift'
end
