ruby '2.3.0'
source 'https://rubygems.org'

gem 'rails', '4.2.5.2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'
gem 'react-rails'
gem 'bootstrap-sass'
gem "font-awesome-rails"
gem 'dotenv'
gem 'rpush'
gem 'administrate', '~> 0.1.4'
gem 'sinatra', require: false
gem 'rack-timeout'
gem 'sidekiq'
gem 'geocoder'
gem 'gmaps4rails'

group :production do
  gem 'pg'
  gem 'rails_12factor'
  gem 'unicorn'
  gem 'newrelic_rpm'
end

group :development, :test do
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'timecop'
end

group :development do
  gem 'sqlite3'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'annotate'
end
